package nus.iss.edu.sg.final_project_backend_resumaid;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.google.api.client.util.DateTime;
import com.google.api.services.calendar.model.Event;

import nus.iss.edu.sg.final_project_backend_resumaid.service.GoogleCalService;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class FinalProjectBackendResumaidApplication implements CommandLineRunner {

	@Autowired
	private GoogleCalService googleCalSvc;

	public static void main(String[] args) {
		SpringApplication.run(FinalProjectBackendResumaidApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		// DateTime now = new DateTime(System.currentTimeMillis());
		// List<Event> bookings = googleCalSvc.getFutureEvents(now);
		// System.out.println(">>>>> BOOKINGS: " + bookings);
		// googleCalSvc.setBooking("6vd6demgkqblk76pggdpa0o0a5_20240708T010000Z", "620d4f84");
	}

}
